### ISSUE TITLE
$(inherited) vs. New Xcode Build System

### ISSUE THREAD

**Issue by fabb** [jspahrsummers/xcconfigs#83]
From the release notes of the newest Xcode 9.3 beta 4:

> When an .xcconfig file contains multiple assignments of the same build setting, later assignments using $(inherited) will inherit from earlier assignments when using the new build system. The old build system discards all except the last assignment. This can cause the evaluated result to be different if $(inherited) is used in the value. You can enable a setting to emit a warning if any of these cases are found by running defaults write com.apple.dt.XCBuild EnableCompatibilityWarningsForXCBuildTransition YES. (37833468)

This could be problematic when an xcconfig should overwrite a build setting that was set in another imported xcconfig.
I have not yet checked if this is already the case for this repo alone, but we definitely have that issue in our app, as we have our own xcconfigs where we import the xcconfigs from this repo vanilla, and overwrite specific build settings.

**Comment by diederich** [comment]
Thanks for posting this, I actually missed it in the release notes, but I think this is great news and will allow much easier adjustments.

If I understand this correctly, this should work great with your setup - as you can now decide if you want to inherit the previous value (via X=$(inherited) xxx), or if you actually wanna overwrite the defaults provided in this xcconfigs.

I switched to a different approach a while ago: using this xcconfigs as the base, and do all the overwrites at the xcproject-level. One of the reasons was actually because we weren't able to reuse previously configured values from the xcconfigs, which is now possible, at least with the new build system..

**Comment by fabb** [comment]
> you can now decide if you want to inherit the previous value (via X=$(inherited) xxx), or if you actually wanna overwrite the defaults provided in this xcconfigs

that's true, but if you want to inherit settings from the level above, but not from the imports on the same level, this is no longer possible. but that should not be a problem, as we import these settings in an xcconfig that is set for the **project** level, and the only parent level is the `iOS defaults` level which does not include too many interesting settings.

**Comment by fabb** [comment]
```
The assignment of 'LD_RUNPATH_SEARCH_PATHS' at "./iOS/iOS-Base.xcconfig:11" uses $(inherited). In the new build system this will inherit from an earlier definition of 'LD_RUNPATH_SEARCH_PATHS' in this xcconfig file or its imports; the old build system would discard earlier definitions. This may result in changes to resolved build setting values.
```

**Comment by diederich** [comment]
@fabb This message is fine though - right?

I had the warnings enabled as well via 
`defaults write com.apple.dt.XCBuild EnableCompatibilityWarningsForXCBuildTransition -bool YES`

and given this is the only one that appears, I think we're safe.

**Comment by fabb** [comment]
We should be good, running like this in production for a few months now.
