### ISSUE TITLE
Consistent Platform Naming

### ISSUE THREAD

**Issue by Abizern** [jspahrsummers/xcconfigs#86]
Before I raise a PR for this:

Currently, the platform names are inconsistent. `watchOS` and `tvOS` and `iOS` match the usual platform names, but not `Mac OS X`. This sort of bothers me and I'd like to rename it to `macOS` for consistency.

Not sure how people will feel about having to relink to the newly named files after pulling these changes though.

Thoughts?

**Comment by diederich** [comment]
Hm - good call and good questions.
Given I've never realised, I guess I'd vote for not changing for now.

... I definitely understand and appreciate the thought of cleaning up though ... :-)

**Comment by mdiep** [comment]
Maybe we could rename but add symlinks from the old names to the new names?

**Comment by gek15** [comment]
U

**Comment by mattrubin** [comment]
I've opened PR #91 with an implementation of the symlinks approach.

One question that remains to be answered: Is there a plan for deprecating and eventually removing these symlinks, or will they remain indefinitely? [As far as I can tell](https://pewpewthespells.com/blog/xcconfig_guide.html), there's no way to create a custom deprecation warning from inside an xcconfig file.

**Comment by mdiep** [comment]
I think the symlinks just need to exist long enough for people to move over. As long as you can say "use this revision, then migrate", I think we're good.

**Comment by diederich** [comment]
> Is there a plan for deprecating and eventually removing these symlinks, or will they remain indefinitely?

Yeah, I guess that's an excellent question. If they're gonna be removed at one point in the future, and then forcing people to move over, I guess it might actually be better to do it right now. (Also given _less_ people will have that pain then).

Also, what happens if you drop the new structure including the symlinks into a project? Does this look any good / does it create any issues?

**Comment by diederich** [comment]
@mattrubin / @mdiep Thoughts on this?

Like I said, I'm not sure the symlinking actually helps, given we wanna remove them at one point anyways, it feels more like dragging old things around. Given there's no deprecation warning, I'm either happy with keeping them as is, or doing the 'hard change' :-)

**Comment by mdiep** [comment]
I'm good with that

**Comment by mattrubin** [comment]
To answer @diederich's earlier question: When you drop the new folder structure including the symlinks into a project, you get file references with both the "Mac OS X" and "macOS" names. Xcode doesn't give any indication that the former are symlinks to the latter, so it's unclear from within the Xcode project why there are two different folders of Mac configs.

Another approach – instead of symlinks – is using shim xcconfig files, where each files at an old path contains nothing but an `#include` statement referencing the corresponding new file. You can see what that looks like in this diff: https://github.com/jspahrsummers/xcconfigs/compare/master...mattrubin:macOS-platform-name-shims

An added benefit of the shim file approach is that it does *sort of* allow for telling the user that the old files are deprecated. As I mentioned above, I can't find a way to trigger a custom deprecation warning from inside an xcconfig, but I have found a way to trigger an error with a useful error message. By adding a `#import` for a bogus file, I can produce an error message like:
`/Users/user/Projects/MyProject/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig:2: could not find included file 'This configuration file ('Mac OS X/Mac-Framework.xcconfig') is deprecated. Please switch to 'macOS/macOS-Framework.xcconfig'.' in search paths (in target 'MyFramework (macOS)')`
Xcode will also produce (when the project is opened) a "Target Integrity" warning that contains the same message. You can see the diff for this approach here: https://github.com/jspahrsummers/xcconfigs/compare/master...mattrubin:macOS-platform-name-shims-with-errors

As I see it, the four options are:
 - Use symlinks (Projects keep compiling as before, but the user has no indication there are new files.)
 - Use xcconfig shims (Projects keep compiling as before, but the user doesn't know there are new files unless they look at the contents of the old ones.)
 - Use xcconfig shims with the bad import hack (Build breaks, but the error message contains clear instructions)
 - Just move the files to the new paths (Build breaks, user is told old files are missing and has to go find the new ones)

I think we're all in agreement that the first two aren't good solutions. So is it worth adding shims which trigger error messages containing migration instructions, or is it simplest to just remove the old files and trust the users will figure out what changed and how to fix it?

**Comment by diederich** [comment]
@mattrubin Thanks for digging into this! 

+1 on the "if we break your build, we also help you how to fix it" option 3) in your list. 

Combining this with the new warnings out of #92, people might not get too angry on us :-)

**Comment by mattrubin** [comment]
I've updated https://github.com/jspahrsummers/xcconfigs/pull/91 to reflect the new approach.
