### ISSUE TITLE
bump to version >= 1.0 runs into error

### ISSUE THREAD

**Issue by hannesa2** [jspahrsummers/xcconfigs#99]
Sorry, I've a Xcode beginner, but I try to bring https://github.com/gitx/objective-git back to live and want support Apple Silicon.
Doing so, I update `xcconfig` to recent commit, to have this ff66306b3164f41f
But I run into this https://github.com/gitx/objective-git/pull/48
```
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-StaticLibrary.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-StaticLibrary.xcconfig') is deprecated. Please use 'macOS/macOS-StaticLibrary.xcconfig' instead.' in search paths
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-StaticLibrary.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-StaticLibrary.xcconfig') is deprecated. Please use 'macOS/macOS-StaticLibrary.xcconfig' instead.' in search paths
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-StaticLibrary.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-StaticLibrary.xcconfig') is deprecated. Please use 'macOS/macOS-StaticLibrary.xcconfig' instead.' in search paths
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-Framework.xcconfig') is deprecated. Please use 'macOS/macOS-Framework.xcconfig' instead.' in search paths
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-Framework.xcconfig') is deprecated. Please use 'macOS/macOS-Framework.xcconfig' instead.' in search paths
/Users/hannes/git/gitx/External/objective-git/Carthage/Checkouts/xcconfigs/Mac OS X/Mac-Framework.xcconfig:8:1: error: could not find included file 'This configuration file ('Mac OS X/Mac-Framework.xcconfig') is deprecated. Please use 'macOS/macOS-Framework.xcconfig' instead.' in search paths
** ARCHIVE FAILED **
```

The suggested solution is not understandable for me. -sorry-

What should I do here _exactly_ to make it work ? Thank you !

**Comment by diederich** [comment]
It looks like Objective-Git uses the outdated xcconfig files. They have been renamed a while ago.

If you open the Xcode workspace, you can configure the used xcconfig files here:

<img width="878" alt="Screenshot 2022-02-22 at 17 01 59" src="https://user-images.githubusercontent.com/61170/155171051-abd6e7b6-9d3a-4340-a313-4c3ee18d7ad8.png">

Does that help?

**Comment by hannesa2** [comment]
I'm a bloody Xcode beginner and I've to say: Sorry, I don't know what to do here.
This is like it looks like currently on my side:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/3314607/155205909-28b02a6c-1213-424c-93c7-e7ea84831245.png">
For me it's the same like your screenshot

Btw, you already checked the repo out and maybe you want to contribute to the best macOS git client ?

**Comment by diederich** [comment]
Thanks Hannes - I did indeed check it out to see, and just now switched to your `BumpXcconfig` branch. Few steps to make it work again:

1. In Xcode, in the project navigator, add the new "macOS" folder from the xcconfigs checkout via drag'n'ndrop (keep any targets unchecked, otherwise Xcode copies the xcconfig into the final package)
2. Once that's in, you can pick the new xcconfig files as shown here:
<img width="1151" alt="Screenshot 2022-02-23 at 18 14 25" src="https://user-images.githubusercontent.com/61170/155371545-5c00b1cc-ccb3-42af-89c3-682288cc464a.png">
3. Once you switched all the xcconfigs over, you can drop the old `Mac OS X` folder from xcconfigs. Then it should look something like this: <img width="1161" alt="Screenshot 2022-02-23 at 18 17 19" src="https://user-images.githubusercontent.com/61170/155371883-c6f1a975-fa3a-45c4-90d4-6331a2a78539.png">
